name: music-audio-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - audioread=2.1.8
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - cycler=0.10.0
  - decorator=4.4.2
  - ffmpeg=4.3
  - freetype=2.10.2
  - gettext=0.19.8.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - icu=64.2
  - joblib=0.16.0
  - jpeg=9d
  - kiwisolver=1.2.0
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libogg=1.3.2
  - libopenblas=0.3.10
  - libpng=1.6.37
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libvorbis=1.3.7
  - libwebp-base=1.1.0
  - llvm-tools=9.0.1
  - llvmdev=9.0.1
  - llvmlite=0.33.0
  - lz4-c=1.9.2
  - matplotlib-base=3.3.0
  - ncurses=6.2
  - nettle=3.4.1
  - numba=0.50.1
  - numpy=1.19.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1g
  - pillow=7.2.0
  - pip=20.1.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pysoundfile=0.10.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - readline=8.0
  - resampy=0.2.2
  - scikit-learn=0.23.1
  - scipy=1.5.1
  - setuptools=49.2.0
  - six=1.15.0
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - wheel=0.34.2
  - x264=1!152.20180806
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
